import Head from 'next/head';
import Main from '../components/Main';
import { useHasMounted } from '../hooks';
export default function Home() {
  const hasMounted = useHasMounted();
  if (!hasMounted) return <></>;
  return (
    <div className="bg-black flex flex-col">
      <Head>
        <title>ChordBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
    </div>
  );
}
